import {StyleSheet, Dimensions, StatusBar} from 'react-native';
import {ThemeColors, ThemeFonts} from '../utils/Theme';
const {width, height} = Dimensions.get('window');
const statusBarHeight = Platform.OS === 'android' ? StatusBar.currentHeight : 0;

export default StyleSheet.create({
  ScrollViewContentContainerStyle: {
    flex: 1,
    backgroundColor: ThemeColors?.WHITE,
  },
  MainContainer: {
    flex: 1,
    backgroundColor: ThemeColors.WHITE,
  },
  CreateAddBTnView: {
    borderRadius: 10,
    borderColor: '#6DA75B',
    borderWidth: 1,
    borderStyle: 'dashed',
    paddingVertical: 15,
  },
  CreateAddBTnText: {
    fontSize: 15,
    textAlign: 'center',
    fontFamily: ThemeFonts.REGULAR,
    color: '#6DA75B',
  },
  SearchFieldView: {
    borderRadius: 10,
    paddingVertical: 6,
    backgroundColor: '#F5F5F5',
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
  },
  FeaturedText: {
    fontSize: 15,
    fontFamily: ThemeFonts.REGULAR,
    color: ThemeColors?.BLACK,
  },
  HealingText: {
    fontSize: 15,
    fontFamily: ThemeFonts.SEMI_BOLD,
    color: ThemeColors?.BLACK,
    textAlign: 'center',
  },
  GrayDivider: {
    width: width,
    height: 1,
    backgroundColor: ThemeColors?.DARK_GRAY,
  },
  AnchorText: {
    fontSize: 15,
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors?.BLACK,
    paddingHorizontal: 20,
    marginTop: 20,
  },
  LogoText: {
    fontSize: 15,
    textAlign: 'center',
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors.BLACK,
  },
  LoginDetailsHeading: {
    fontSize: 20,
    fontFamily: ThemeFonts.SEMI_BOLD,
    color: ThemeColors.BLACK,
    textAlign: 'center',
  },
  TextInputStyle: {
    width: width - 50,
    height: 51,
    borderRadius: 10,
    backgroundColor: '#F5F5F5',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  LoginButtonStyle: {
    width: width - 50,
    height: 51,
    borderRadius: 10,
    backgroundColor: '#6DA75B',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  LoginBtnTExt: {
    fontSize: 15,
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors.WHITE,
    textAlign: 'center',
  },
  ActiveGroupItem: {
    width: width - 50,
    alignSelf: 'center',
    borderRadius: 10,
    borderColor: ThemeColors?.DARK_GRAY,
    borderWidth: 1,
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  NameTExt: {
    fontSize: 15,
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors.BLACK,
  },
  DescText: {
    fontSize: 10,
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors.DARK_GRAY,
  },
  GrayRound: {
    width: 28,
    height: 28,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F0EFEF',
  },
  PrayNowText: {
    fontSize: 10,
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors.BLACK,
    textAlign: 'center',
  },
  GreenRoundView: {
    width: 50,
    height: 50,
    borderRadius: 30,
    backgroundColor: '#284D07',
    alignItems: 'center',
    justifyContent: 'center',
  },
  AText: {
    fontSize: 20,
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors.WHITE,
  },
  AdamNameText: {
    fontSize: 11,
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors.BLACK,
    marginTop: 5,
  },
  AdamDescText: {
    fontSize: 10,
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors.DARK_GRAY,
    marginTop: -5,
  },
  ColorsRoundView: {
    width: 41,
    height: 41,
    borderRadius: 28,
    backgroundColor: '#284D07',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 5,
  },
  BText: {
    fontSize: 15,
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors.WHITE,
  },
  CommentOrMessageView: {
    width: width - 120,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 25,
    backgroundColor: '#EDEDED',
    alignSelf: 'center',
    paddingVertical: 5,
  },
  CommentOrMessageText: {
    fontSize: 15,
    fontFamily: ThemeFonts.MEDIUM,
    color: '#6DA75B',
  },
  ContactRenderItemView: {
    backgroundColor: ThemeColors?.LIGHT_GRAY,
    width: width - 50,
    alignSelf: 'center',
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginVertical: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  NameTextItem: {
    fontSize: 14,
    fontFamily: ThemeFonts.BOLD,
    color: ThemeColors?.BLACK,
  },
  ContactTextItem: {
    fontSize: 12,
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors?.BLACK,
  },
  DontBtnView: {
    backgroundColor: '#4CBB17',
    width: width - 50,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    paddingVertical: 15,
    marginTop: 20,
  },
  DoneTextBtn: {
    fontSize: 15,
    fontFamily: ThemeFonts.BOLD,
    color: ThemeColors?.WHITE,
  },
  ApproveBtnView: {
    width: 90,
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    backgroundColor: ThemeColors?.DARK_GRAY,
  },
  ApproveBtnText: {
    fontSize: 12,
    fontFamily: ThemeFonts.SEMI_BOLD,
    color: ThemeColors?.WHITE,
  },
});
