import {StyleSheet, Dimensions, StatusBar} from 'react-native';
import {ThemeColors, ThemeFonts} from '../utils/Theme';
const {width, height} = Dimensions.get('window');
const statusBarHeight = Platform.OS === 'android' ? StatusBar.currentHeight : 0;

export default StyleSheet.create({
  ScrollViewContentContainerStyle: {
    flex: 1,
    backgroundColor: ThemeColors?.WHITE,
  },
  MainContainer: {
    flex: 1,
    backgroundColor: ThemeColors.WHITE,
  },
  CreateAddBTnView: {
    borderRadius: 10,
    borderColor: '#6DA75B',
    borderWidth: 1,
    borderStyle: 'dashed',
    paddingVertical: 15,
  },
  CreateAddBTnText: {
    fontSize: 15,
    textAlign: 'center',
    fontFamily: ThemeFonts.REGULAR,
    color: '#6DA75B',
  },
  SearchFieldView: {
    borderRadius: 10,
    paddingVertical: 6,
    backgroundColor: '#F5F5F5',
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
  },
  FeaturedText: {
    fontSize: 15,
    fontFamily: ThemeFonts.REGULAR,
    color: ThemeColors?.BLACK,
  },
  HealingText: {
    fontSize: 15,
    fontFamily: ThemeFonts.SEMI_BOLD,
    color: ThemeColors?.BLACK,
    textAlign: 'center',
  },
  GrayDivider: {
    width: width,
    height: 1,
    backgroundColor: ThemeColors?.DARK_GRAY,
  },
  AnchorText: {
    fontSize: 15,
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors?.BLACK,
    paddingHorizontal: 20,
    marginTop: 20,
  },
  LogoText: {
    fontSize: 15,
    textAlign: 'center',
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors.BLACK,
  },
  LoginDetailsHeading: {
    fontSize: 20,
    fontFamily: ThemeFonts.SEMI_BOLD,
    color: ThemeColors.BLACK,
    textAlign: 'center',
  },
  TextInputStyle: {
    width: width - 50,
    height: 51,
    borderRadius: 10,
    backgroundColor: '#F5F5F5',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  LoginButtonStyle: {
    width: width - 50,
    height: 51,
    borderRadius: 10,
    backgroundColor: '#6DA75B',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  LoginBtnTExt: {
    fontSize: 15,
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors.WHITE,
    textAlign: 'center',
  },
  FirstSectionView: {
    width: width - 50,
    alignSelf: 'center',
    borderRadius: 10,
    borderColor: ThemeColors?.DARK_GRAY,
    borderWidth: 1,
  },
  CurrentText: {
    fontSize: 10,
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors.BLACK,
    textAlign: 'center',
  },
  DaysText: {
    fontSize: 10,
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors.BLACK,
    textAlign: 'center',
  },
  HorizontalView: {
    flexDirection: 'row',
    width: width - 50,
    justifyContent: 'center',
  },
  GrayDividerTwo: {
    backgroundColor: '#DBDBDB',
    width: width / 2 + 20,
    alignSelf: 'center',
    height: 1,
  },
  HeadingText: {
    fontSize: 10,
    fontFamily: ThemeFonts.REGULAR,
    color: ThemeColors.DARK_GRAY,
    textAlign: 'center',
  },
  CenteredView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: width - 100,
    alignSelf: 'center',
    marginVertical: 15,
  },
  LongestStreakText: {
    fontSize: 10,
    fontFamily: ThemeFonts.REGULAR,
    color: ThemeColors.DARK_GRAY,
    textAlign: 'center',
  },
  WeeklyText: {
    fontSize: 15,
    fontFamily: ThemeFonts.SEMI_BOLD,
    color: ThemeColors.BLACK,
  },
  NumbersTExt: {
    fontSize: 30,
    fontFamily: ThemeFonts.BOLD,
    color: ThemeColors.BLACK,
  },
  NumbersUbTExt: {
    fontSize: 10,
    fontFamily: ThemeFonts.SEMI_BOLD,
    color: ThemeColors.BLACK,
    marginTop: -18,
  },
  completedText: {
    fontSize: 10,
    fontFamily: ThemeFonts.REGULAR,
    color: ThemeColors.BLACK,
    marginTop: 5,
  },
  weekText: {
    fontSize: 15,
    fontFamily: ThemeFonts.MEDIUM,
    color: ThemeColors.BLACK,
    marginTop: 5,
  },
  SessionText: {
    fontSize: 10,
    fontFamily: ThemeFonts.REGULAR,
    color: ThemeColors.BLACK,
    textAlign: 'center',
  },
  NumbersTExt2: {
    fontSize: 22,
    fontFamily: ThemeFonts.BOLD,
    color: ThemeColors.BLACK,
  },
  NumbersUbTExt2: {
    fontSize: 7,
    fontFamily: ThemeFonts.SEMI_BOLD,
    color: ThemeColors.BLACK,
    marginTop: -13,
  },
  VarshView: {
    backgroundColor: '#ABD6DF',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
  },
  PrayginText: {
    fontSize: 15,
    fontFamily: ThemeFonts.REGULAR,
    color: ThemeColors.BLACK,
  },
  VarshView2: {
    backgroundColor: ThemeColors.WHITE,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
  },
  RawView: {
    flexDirection: 'row',
  },
  ZeroText: {
    fontSize: 37,
    fontFamily: ThemeFonts.REGULAR,
    color: ThemeColors.BLACK,
  },
  ZeroSubText: {
    fontSize: 15,
    fontFamily: ThemeFonts.REGULAR,
    color: ThemeColors.BLACK,
    marginTop: 2,
    marginLeft: 5,
  },
  Datetext: {
    fontSize: 15,
    fontFamily: ThemeFonts.REGULAR,
    color: ThemeColors.BLACK,
    textAlign: 'center',
    marginBottom: 10,
  },
});
