# Use environment variable IOS_DEPLOYMENT_TARGET if set, else default to 14.0
ios_deployment_target = ENV['IOS_DEPLOYMENT_TARGET'] || '14.0'
platform :ios, ios_deployment_target

require_relative '../node_modules/react-native/scripts/react_native_pods'

# Disable Flipper completely to avoid build script errors
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AnchorPrayer' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'AnchorPrayerTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    installer.pods_project.build_configurations.each do |config|
      # Exclude arm64 architecture on simulator (fix M1 Mac builds)
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
